* File: nor.pex.netlist.NOR.pxi
* Created: Mon Feb 25 21:53:08 2019
* 
x_PM_NOR_VDD N_VDD_M2_b N_VDD_M2_s VDD PM_NOR_VDD
x_PM_NOR_GROUND N_GROUND_M0_s N_GROUND_M1_d N_GROUND_M0_b GROUND PM_NOR_GROUND
x_PM_NOR_Y N_Y_M0_d N_Y_M3_d N_Y_c_1_p Y PM_NOR_Y
x_PM_NOR_B N_B_M0_g N_B_M2_g B PM_NOR_B
x_PM_NOR_A N_A_M3_g N_A_M1_g A PM_NOR_A
cc_1 N_Y_c_1_p N_A_M1_g 4.394f
