* File: Inverter.pex.netlist.INVERTER.pxi
* Created: Fri Feb 15 13:17:47 2019
* 
x_PM_INVERTER_VDD N_VDD_M1_b N_VDD_M1_s VDD PM_INVERTER_VDD
x_PM_INVERTER_GROUND N_GROUND_M0_s N_GROUND_M0_b GROUND PM_INVERTER_GROUND
x_PM_INVERTER_OUT N_OUT_M0_d N_OUT_M1_d OUT PM_INVERTER_OUT
x_PM_INVERTER_IN N_IN_M0_g N_IN_M1_g IN PM_INVERTER_IN
